const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),{webcrypto}=require('node:crypto');
const dbSource=fs.readFileSync('js/db.js','utf8').replace('export const DB =','const DB =')+'\nglobalThis.DB=DB;';
const data='data:image/jpeg;base64,aW1hZ2UtZml4dHVyZQ==', bytes=Buffer.from('image-fixture');
function dbHarness(){let uploads=0,body,inserted,updated;const h={bad:false,fail:false};const bucket={upload:async()=>{uploads++;return {error:h.fail?{message:'Storage unavailable'}:null}},getPublicUrl:()=>({data:{publicUrl:'https://example.invalid/photo.jpg'}})};const ctx={console,crypto:webcrypto,AbortController,setTimeout,clearTimeout,fetch:async url=>String(url).startsWith('data:')?new Response(bytes,{headers:{'Content-Type':'image/jpeg'}}):new Response(h.bad?'wrong':bytes,{status:h.fail&&h.bad?404:200}),supabase:{createClient:()=>({storage:{from:()=>bucket},from:()=>({insert:async value=>{inserted=value;return{error:null}},update:value=>({eq:async()=>{updated=value;return{error:null}}})})})}};vm.createContext(ctx);vm.runInContext(dbSource,ctx);return {...h,ctx,db:ctx.DB,set:(k,v)=>h[k]=v,uploads:()=>uploads,inserted:()=>inserted,updated:()=>updated};}
class Element {constructor(){this.listeners={};this.children=[];this.style={};this.hidden=false;}addEventListener(n,f){this.listeners[n]=f}append(...children){this.children.push(...children)}insertAdjacentElement(_,el){this.after=el}closest(){return this.form}fire(n,event={}){return this.listeners[n]?.(event)}}
function uiHarness(){const form=new Element(),input=new Element();input.form=form;input.parentElement=new Element();input.files=[];const photos=[];let fail=true,uploads=0;const ctx={console:{warn(){}},window:{},document:{createElement:()=>new Element()},DB:{uploadPhotoToStorage:async()=>{uploads++;if(fail)throw Error('offline');return 'https://example.invalid/ok.jpg'}},Toast:{error(){},info(){}}};let source=fs.readFileSync('js/ui.js','utf8').replace(/^\uFEFF/, '').replace(/^import .*;\r?\n/gm,'').replaceAll('export const ','const ')+'\nglobalThis.UI=UI;';vm.createContext(ctx);vm.runInContext(source,ctx);ctx.UI.compressImage=async()=>data;ctx.UI.bindPhotoUpload(input,photos,()=>{},5);return{form,input,photos,status:input.parentElement.after,setFail:v=>fail=v,uploads:()=>uploads,flush:async()=>{for(let i=0;i<30;i++)await Promise.resolve()}};}
(async()=>{
const a=dbHarness();assert.equal(await a.db.uploadPhotoToStorage('https://example.invalid/existing'),'https://example.invalid/existing');assert.equal(a.uploads(),0);console.log('PASS existing URLs unchanged');
assert.equal(await a.db.uploadPhotoToStorage(data),'https://example.invalid/photo.jpg');assert.equal(a.uploads(),1);console.log('PASS verified upload returns URL');
a.set('fail',true);assert.equal(await a.db.uploadPhotoToStorage(data),'https://example.invalid/photo.jpg');console.log('PASS duplicate/retry accepted only with matching image');
a.set('bad',true);await assert.rejects(a.db.uploadPhotoToStorage(data));console.log('PASS failed or mismatched upload never returns Base64');
await assert.rejects(a.db.uploadPhotoToStorage('data:text/html;base64,YQ=='));console.log('PASS invalid photo format rejected');
a.set('bad',false);a.set('fail',false);await a.db.sbInsertDailyLog({id:'fixture',photos:[data],note:'unchanged'},'p');assert.equal(a.inserted().photos[0],'https://example.invalid/photo.jpg');assert.equal(a.inserted().note,'unchanged');await a.db.sbUpdateDailyLog('fixture',{note:'keep',photos:[data]});assert.equal(a.updated().photos[0],'https://example.invalid/photo.jpg');assert.equal(a.updated().note,'keep');console.log('PASS older cached Base64 converted on insert/edit; other fields preserved');
const u=uiHarness();u.input.files=[{name:'fixture.jpg'}];u.input.fire('change');let blocked=false;u.form.fire('submit',{preventDefault(){blocked=true},stopImmediatePropagation(){}});assert.ok(blocked);await u.flush();assert.equal(u.photos.length,0);assert.equal(u.status.hidden,false);assert.equal(u.status.children[1].hidden,false);console.log('PASS failed file retained and submit blocked');
u.setFail(false);u.status.children[1].fire('click');await u.flush();assert.equal(u.photos.length,1);assert.equal(u.status.hidden,true);blocked=false;u.form.fire('submit',{preventDefault(){blocked=true},stopImmediatePropagation(){}});assert.equal(blocked,false);console.log('PASS retry succeeds once and enables submit');
u.setFail(true);u.input.files=[{name:'other.jpg'}];u.input.fire('change');await u.flush();u.status.children[2].fire('click');assert.equal(u.status.hidden,true);assert.equal(u.photos.length,1);console.log('PASS cancel pending file preserves successful attachments');
console.log('9 phase-2 checks passed; no network or production writes.');
})().catch(e=>{console.error(e);process.exitCode=1});
