-- Additive migration: does not modify or delete existing business data.
create extension if not exists pg_cron with schema pg_catalog;
create extension if not exists pg_net with schema extensions;
create extension if not exists supabase_vault with schema vault;

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id text not null references public.users(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  platform text not null default 'other',
  user_agent text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists push_subscriptions_user_active_idx
  on public.push_subscriptions(user_id, active);

alter table public.push_subscriptions enable row level security;
revoke all on table public.push_subscriptions from anon, authenticated;

-- Called by pg_cron. The shared secret is held in Supabase Vault, never in Git.
create or replace function public.invoke_daily_push_reminder()
returns void
language plpgsql
security definer
set search_path = public, vault, extensions
as $$
declare
  cron_secret text;
begin
  select decrypted_secret into cron_secret
  from vault.decrypted_secrets
  where name = 'push_cron_secret'
  order by created_at desc
  limit 1;

  if cron_secret is null then
    raise warning 'push_cron_secret is missing; reminder was not invoked';
    return;
  end if;

  perform net.http_post(
    url := 'https://qadsqfhvrhdmpjpexews.supabase.co/functions/v1/push-notifications',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'x-cron-secret', cron_secret
    ),
    body := '{"action":"daily_reminder"}'::jsonb,
    timeout_milliseconds := 15000
  );
end;
$$;

revoke all on function public.invoke_daily_push_reminder() from public, anon, authenticated;

do $$
declare existing_job bigint;
begin
  select jobid into existing_job from cron.job where jobname = 'mtp-daily-report-reminder' limit 1;
  if existing_job is not null then perform cron.unschedule(existing_job); end if;
end $$;

-- 10:00 UTC = 17:00 Asia/Ho_Chi_Minh. 1-6 means Monday through Saturday.
select cron.schedule(
  'mtp-daily-report-reminder',
  '0 10 * * 1-6',
  'select public.invoke_daily_push_reminder();'
);

